Review PR
TNBase/takeoff-dataiku pull request #1
Opened 2024-03-08 10:02 UTC by fergusbarratt

This PR contains all of the content of main, for review

2024-03-11 18:15 UTC, MayeulRousselet requested changes
My review is only about plugin development best practices:
- It lacks a CHANGELOG file that can be found here:  https://github.com/dataiku/dss-plugin-template/blob/main/CHANGELOG.md
- It lacks a Makefile to let us build the plugin, here is an example (beware it use gradle as build system, just replace the gradle command by ant ones).:
```
PLUGIN_ID=`cat plugin.json | python -c "import sys, json; print(str(json.load(sys.stdin)['id']).replace('/',''))"`
PLUGIN_VERSION=`cat plugin.json | python -c "import sys, json; print(str(json.load(sys.stdin)['version']).replace('/',''))"`

build-plugin:
	@./gradlew test
	@./gradlew dist
	@cat plugin.json|json_pp > /dev/null

zip-plugin:
	@rm -rf dist
	@mkdir dist
	@zip -r dist/dss-plugin-${PLUGIN_ID}-${PLUGIN_VERSION}.zip plugin.json lib

plugin: build-plugin zip-plugin
```

2024-03-11 18:15 UTC, MayeulRousselet commented on titan-ml-connector.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be added in the .gitignore file

2024-03-12 10:22 UTC, fergusbarratt commented
Great - thanks for your review. Will get on these ASAP

2024-03-13 10:30 UTC, adamnellis requested changes
Nice plugin - thank you 😁 

The code looks good in general, and I still need to test it. 

I just spotted one change that needs to be made, that you couldn't have known about 😅  so letting you know this now before I start testing it.

2024-03-13 10:30 UTC, adamnellis commented on java-llms/titanMLConnector/com/titanml/llm/TitanMLLLMConnector.java
> +        };
The `ExternalJsonAPIClient` has changed a little in DSS version 12.5.2. The lowest DSS version that we are supporting for LLM plugins is 12.5.2

So you should upgrade your DSS to 12.5.2, and change this code to the new version.
(NB: I didn't test this code in the plugin, so double check that this works well for you and that I didn't make a typo 😅)
```suggestion
        Consumer<HttpClientBuilder> customizeBuilderCallback = (builder) -> {  
            builder.setRedirectStrategy(new LaxRedirectStrategy());  
            HTTPBasedLLMNetworkSettings networkSettings = new HTTPBasedLLMNetworkSettings();  
            OnlineLLMUtils.add429RetryStrategy(builder, networkSettings);  
        };
        client = new ExternalJSONAPIClient(endpointUrl, null, true, null, customizeBuilderCallback);  
```

2024-03-15 16:11 UTC, adamnellis commented on java-llms/titanMLConnector/com/titanml/llm/TitanMLLLMConnector.java
> +        };
FYI: I've tested this, and the modification I provided above works, if we add in the import: `import java.util.function.Consumer;`

2024-03-15 16:49 UTC, adamnellis requested changes
✅ The instructions for setting up the takeoff server are very comprehensive and easy to follow - thank you 🙂 

💥 It didn't format the URL correctly for me, but I managed to fix it with a small change (see comment below)

💥 We need to make a small change to have this be compatible with DSS version 12.5.2 (see comment above)

✅ When it was running, the text generation and embedding LLMs worked well

✅ I like the detail in the readme, including examples of how to use the LLMs in a Dataiku workflow

💥 I have some questions about the readme (see comments below)

2024-03-15 16:49 UTC, adamnellis commented on java-llms/titanMLConnector/com/titanml/llm/TitanMLLLMConnector.java
> +            JsonObject response = client.postObjectToJSON(":3000/generate", JsonObject.class, jsonObject);
⚠️  Unfortunately, this didn't work for me as-is. But I did get it working with a small modification.

---

Perhaps it's because I am using localhost, and `ssh -L 3000:localhost:3000 -L 3001:localhost:3001 ubuntu@<HOSTNAME>` to access my takeoff instance.

But for me, when I entered `http://localhost` as the endpoint URL, it was giving me `http://localhost/:3000/generate`, which is wrong (should be `http://localhost:3000/generate`).

---

I fixed this by moving the port number from here into the initialisation of `ExternalJSONAPIClient` above.

So we have this in `init`:
```java
client = new ExternalJSONAPIClient(endpointUrl + ":3000", null, true, null, customizeBuilderCallback);
```

And this in `completeBatch`:
```java
JsonObject response = client.postObjectToJSON("generate", JsonObject.class, jsonObject);
```

And this in `embedBatch`:
```java
JsonObject response = client.postObjectToJSON("embed", JsonObject.class, jsonObject);
```

2024-03-15 16:49 UTC, adamnellis commented on README.md
> +generation model, and one for the image generation model. The different
We can create separate connections for each model. 

We can also create one connection and add three separate models to it.

This is the preferred way to do it in DSS: having one connection with multiple models in it.

![Screenshot 2024-03-15 at 16 28 08](https://github.com/TNBase/takeoff-dataiku/assets/13545980/bea3092b-b385-453e-9671-e7ea7e060438)

2024-03-15 16:49 UTC, adamnellis commented on README.md
> +::: Note
Is this `:::` syntax a copy-paste from a different markup language? 

Because it's not recognised by Github's markdown renderer.

2024-03-15 16:49 UTC, adamnellis commented on README.md
> +:::
Ditto for the `:::` syntax.

2024-03-15 16:49 UTC, adamnellis commented on README.md
> +# Contributing
Are we missing some text here?

We say at the top of this section `we're going to build 3 LLM workflows that transform that dataset` but then we only describe one of the workflows.

2024-03-20 12:06 UTC, JoshC8C7 commented
Thanks for everyone's comments - I've addressed them all so feel free to re-review the PR now!

2024-03-26 15:31 UTC, MayeulRousselet requested changes
Thanks for the fixes, just 3 smalls changes for me

2024-03-26 15:31 UTC, MayeulRousselet commented on makefile
> +PLUGIN_ID=`cat plugin.json | python -c "import sys, json; print(str(json.load(sys.stdin)['id']).replace('/',''))"`
Rename the file to 'Makefile'

2024-03-26 15:31 UTC, MayeulRousselet commented on makefile
> +	ant -f build.xml -Denv.DKUINSTALLDIR=${DATAIKU_INSTALL}
`DKUINSTALLDIR` is a standard vairable set by DSS when running the DSS binary and that should point to the kit folder. Just run the make command:
`DKUINSTALLDIR=/path/to/kit make plugin`

2024-03-26 15:31 UTC, MayeulRousselet commented on plugin.json
> +    "url": "https://docs.titanml.co/docs/Docs/integrations/dataiku",
URL is 404 for now, expected?

2024-03-26 17:30 UTC, adamnellis requested changes
Thanks for those changes. 

I found one issue in the `Makefile` that needs fixing.

2024-03-27 14:24 UTC, JoshC8C7 commented on plugin.json
> +    "url": "https://docs.titanml.co/docs/Docs/integrations/dataiku",
fixed :)

2024-03-28 08:11 UTC, MayeulRousselet approved these changes
Ok for me thanks!!!

2024-04-10 17:02 UTC, adamnellis approved these changes
Looks good to me! 

---

✅ Tested that the makefile builds the plugin correctly

✅ Tested a text generation model and an embedding model

✅ Followed the instructions in the readme to check that they are good
- I encountered some issues setting up the Takeoff instance, but we fixed these in Josh's latest commits to the readme.

2024-04-11 09:07 UTC, merged